### ISSUE TITLE
无法打包iOS

### ISSUE THREAD

**Issue by GodLikeThomas** [shijia2118/ysPlay#1]
![WechatIMG324](https://user-images.githubusercontent.com/10253785/233529481-286112b2-077a-43cc-a9d5-29be3c4a9f96.jpeg)

这个要怎么设置呢？

**Comment by shijia2118** [comment]
这个问题我也发现了，正在解决中，今天应该会更新

**Comment by GodLikeThomas** [comment]
我联系了莹石云，他们说没办法解决，我把版本降到4.20.1就可以，但是要改一下代码把一些新功能注释掉才行

**Comment by shijia2118** [comment]
是的。刚才萤石云的客服也是这么回复我的。我正在把sdk版本回退。下班前应该能改完上传

**Comment by shijia2118** [comment]
你好，新版本0.0.5已经发布了，可以正常上传。该版本是把SDK降级到4.20.1了，因为该版本SDK在IOS端的热点配网和声波配网没有失败的回调(5.0+修复了该bug)，所以需要在flutter中自己做一个倒计时，可以参考example下peiwang_page.dart中的dismissAfter30s()方法。五一后，他们应该会针对无法上传appstore的问题，发布一个新版本，到时我这边也会更新。
