### ISSUE TITLE
Xcode15上无法运行

### ISSUE THREAD

**Issue by GodLikeThomas** [shijia2118/ysPlay#2]
莹石云已经更新了SDK支持Xcode15，修复iconv的问题，直接修改版本号的话没办法通过编译，能更新一下吗？

**Comment by shijia2118** [comment]
抱歉啊，最近忙，没关注。我会在今明2天更新，谢谢提醒！

**Comment by shijia2118** [comment]
你好，感谢你使用该插件。但是我可能工作太忙，不一定能及时关注到。下次如果遇到问题，可以联系我微信:228749551@qq.com
