### ISSUE TITLE
flutter pub add 之后ios运行报错

### ISSUE THREAD

**Issue by Durian-j** [shijia2118/ysPlay#3]
flutter引入了 ys_play: ^0.3.0 插件之后，在ios模拟器上运行项目，控制台报错如下：

Failed to build iOS app
Error (Xcode): Undefined symbols:
Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

**Comment by Durian-j** [comment]
Flutter 3.13.9,  Dart 3.1.5, 仅仅是引入 ys_play 插件之后ios运行就会报错

**Comment by shijia2118** [comment]
模拟器没法运行，需要在真机上运行。

**Comment by Yumikolab** [comment]
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_EZDeviceRecordFile

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_EZOpenSDK

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_EZStorageInfo

Could not build the application for the simulator.
Error launching application on iPhone 14.

知道这是什么原因嘛？

**Comment by shijia2118** [comment]
要在真机上运行

**Comment by Yumikolab** [comment]
好的，谢谢，已解决
