### ISSUE TITLE
YS_Play does not allow connection from 'overseas'

### ISSUE THREAD

**Issue by Anna2Bdx** [shijia2118/ysPlay#5]
Hello!

I spent some time in banging my head on my desk in front of my integration of your lib... before realising that your lib is only targeting EZOpenSDK for SDKinit and TokenSet... whereas, for foreigners like me, we are forced to use EZGlobalSDK...

Maybe a change in your lib would allow people like me to find their way... in the meantime, I forked my own version

Anyways, thanks for your work in this integration!

**Comment by shijia2118** [comment]
是的。ys_play依赖是针对我的项目而创建的，它基于EZOpenSDK。如果在使用过程中，有遇到问题，我们可以一起讨论。
